#!/usr/bin/env python3
"""
Place a crystal inside a digitized hoop and write it as a CSG component YAML
ready for generate_scene.py.

The crystal is modelled as an intersection of half-spaces (CSG), generated by
crystal_harvester.crystal_shapes.make_crystal.  Each half-space normal is
derived from the crystal lattice orientation via reciprocal-lattice vectors
(XDS convention).  The half-space offsets are shifted so the crystal is
centred at the loop centroid (same convention as add_droplet.py) plus an
optional user-supplied offset.

Usage
-----
    python3 add_crystal.py hoop.yaml [--output crystal.yaml]
                           [--preset PRESET]      (default: plate)
                           [--dim D [D ...]]      half-widths in mm
                           [--a-axis X Y Z]       real-space a-axis in Å
                           [--b-axis X Y Z]       real-space b-axis in Å
                           [--c-axis X Y Z]       real-space c-axis in Å
                           [--offset DX DY DZ]    shift from loop centroid (mm)

Presets and required --dim values
----------------------------------
  cube       --dim a_half b_half c_half
  plate      --dim ab_half c_half        (thin along c)
  needle     --dim ab_half c_half        (long along c)
  hexagonal  --dim r_half c_half

Full pipeline
-------------
    python3 digitize_fiber.py real_loop.jpg --output hoop.yaml
    python3 add_stem.py   hoop.yaml              # → loop.yaml
    python3 add_droplet.py hoop.yaml             # → droplet.yaml
    python3 add_crystal.py hoop.yaml             # → crystal.yaml
    python3 generate_scene.py loop.yaml droplet.yaml crystal.yaml
    python3 render.py scene.yaml
"""
import sys, os, argparse
sys.path.insert(0, '/home/jamesh/projects/loop_sim/claude')

import numpy as np
import yaml

from crystal_harvester.crystal_shapes import make_crystal


_DEFAULT_OUTPUT = os.path.join(os.path.dirname(__file__), 'crystal.yaml')

# Default lattice: simple cubic (identity orientation)
_DEFAULT_A = [1.0, 0.0, 0.0]
_DEFAULT_B = [0.0, 1.0, 0.0]
_DEFAULT_C = [0.0, 0.0, 1.0]

# Default half-widths (mm): plate crystal, 60 µm wide × 15 µm thick
_PRESET_DEFAULTS = {
    'cube':      [0.03, 0.03, 0.03],
    'plate':     [0.04, 0.01],
    'needle':    [0.01, 0.06],
    'hexagonal': [0.03, 0.02],
}


def parse_args():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument('hoop',
                   help='Digitized hoop YAML (from digitize_fiber.py)')
    p.add_argument('--output', default=_DEFAULT_OUTPUT,
                   help=f'Output component YAML (default: {_DEFAULT_OUTPUT})')
    p.add_argument('--preset', default='plate',
                   choices=['cube', 'plate', 'needle', 'hexagonal'],
                   help='Crystal habit preset (default: plate)')
    p.add_argument('--dim', type=float, nargs='+', default=None,
                   metavar='D',
                   help='Half-widths in mm (number required depends on preset)')
    p.add_argument('--a-axis', type=float, nargs=3, default=_DEFAULT_A,
                   metavar=('X', 'Y', 'Z'),
                   help='Real-space a-axis in Å (default: [1,0,0])')
    p.add_argument('--b-axis', type=float, nargs=3, default=_DEFAULT_B,
                   metavar=('X', 'Y', 'Z'),
                   help='Real-space b-axis in Å (default: [0,1,0])')
    p.add_argument('--c-axis', type=float, nargs=3, default=_DEFAULT_C,
                   metavar=('X', 'Y', 'Z'),
                   help='Real-space c-axis in Å (default: [0,0,1])')
    p.add_argument('--offset', type=float, nargs=3, default=[0.0, 0.0, 0.0],
                   metavar=('DX', 'DY', 'DZ'),
                   help='Displacement from loop centroid in mm (default: 0 0 0)')
    return p.parse_args()


def _loop_centroid(hoop_data):
    """Return (3,) centroid of the loop waypoints (mm)."""
    waypoints = np.array(hoop_data['fiber']['waypoints'], dtype=float)
    if np.allclose(waypoints[0], waypoints[-1]):
        waypoints = waypoints[:-1]
    return waypoints.mean(axis=0)


def _translate_halfspace(hs, center):
    """
    Shift a half-space spec so the crystal is centred at `center`.

    The local half-space is  n·x <= d  where x is crystal-local.
    In world coordinates x_world = x_local + center, so:
        n·(x_world - center) <= d
        n·x_world <= d + n·center
    """
    n = np.array(hs['normal'], dtype=float)
    d = float(hs['offset'])
    new_offset = d + np.dot(n, center)
    return {
        'type':   'half_space',
        'normal': [round(float(v), 8) for v in n],
        'offset': round(float(new_offset), 8),
    }


def main():
    args = parse_args()

    # ------------------------------------------------------------------
    # Resolve crystal dimensions
    # ------------------------------------------------------------------
    dims = args.dim if args.dim is not None else _PRESET_DEFAULTS[args.preset]

    # ------------------------------------------------------------------
    # Load hoop, find loop centroid
    # ------------------------------------------------------------------
    with open(args.hoop) as f:
        hoop_data = yaml.safe_load(f)

    centroid = _loop_centroid(hoop_data)
    center   = centroid + np.array(args.offset, dtype=float)

    print(f"Loop centroid:   ({centroid[0]:+.4f}, {centroid[1]:+.4f}, "
          f"{centroid[2]:+.4f}) mm", file=sys.stderr)
    print(f"Crystal centre:  ({center[0]:+.4f}, {center[1]:+.4f}, "
          f"{center[2]:+.4f}) mm", file=sys.stderr)

    # ------------------------------------------------------------------
    # Build CSG shape in local (crystal-centred) coordinates
    # ------------------------------------------------------------------
    lattice_abc = {
        'a_axis': args.a_axis,
        'b_axis': args.b_axis,
        'c_axis': args.c_axis,
    }

    shape_local, lattice_meta = make_crystal(args.preset, dims, lattice_abc)

    # Translate each half-space to world coordinates
    children_world = [
        _translate_halfspace(hs, center)
        for hs in shape_local['children']
    ]

    shape_world = {
        'type':     'intersection',
        'children': children_world,
    }

    print(f"Preset: {args.preset}  dims={dims}  "
          f"{len(children_world)} half-spaces", file=sys.stderr)

    # ------------------------------------------------------------------
    # Serialise to component YAML
    # ------------------------------------------------------------------
    output = {
        'objects': [
            {
                'name':     'crystal',
                'material': 'crystal',
                'lattice':  lattice_meta,
                'shape':    shape_world,
            }
        ]
    }

    with open(args.output, 'w') as f:
        yaml.dump(output, f, default_flow_style=None, sort_keys=False)

    print(f"Crystal → {args.output}", file=sys.stderr)
    print(f"Next:   python3 generate_scene.py loop.yaml droplet.yaml crystal.yaml",
          file=sys.stderr)


if __name__ == '__main__':
    main()
